encoding: utf-8
lang: zh-CN
title: 第九届编码密码组合研讨会
description:  The Ninth Symposium on Coding Theory, Cryptography and Combinatorics
show_downloads: false
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true  # 启用自动生成ID
  toc_levels: 1..4  # 调整目录层级范围
  header_offset: 1  # 设置标题的偏移量，以便更好地显示目录

google_analytics:
sass:
  style: compressed
